GCC = cc68x

OBJ = hero.o renderer.o model.o event.o const.o raster.o

tst_exc: $(OBJ)
	$(GCC) -g $(OBJ) -o comp

hero.o: hero.c hero.h const.h
	$(GCC) -g -c hero.c

renderer.o: renderer.c renderer.h raster.h const.h
	$(GCC) -g -c renderer.c

event.o: event.c event.h
	$(GCC) -g -c event.c
	
model.o: model.c model.h const.h
	$(GCC) -g -c model.c

const.o: const.c const.h
	$(GCC) -g -c const.c

raster.o: raster.c raster.h
	$(GCC) -g -c raster.c
