/*
Names:  	Enrik Rushiti
			Kiril Sikov

Module:		Menu

Purpose: 	Contains the function(s) related to the splash screen and main menu
*/
#ifndef MENU_H
#define MENU_H

#include <osbind.h>
#include <stdio.h>
#include "const.h"


/* 
Purpose: a menu that is looped while the player is at the splash screen.
Pressing 1 makes the single player game start. Pressing ESC quits the game.
*/
bool splashScreenMenu ();







#endif