GCC = cc68x

OBJ = main.o renderer.o model.o event.o const.o raster.o

tst_exc: $(OBJ)
	$(GCC) -g main.o const.o renderer.o model.o event.o raster.o -o comp

main.o: main.c
	$(GCC) -g -c main.c

renderer.o: renderer.c renderer.h raster.h const.h
	$(GCC) -g -c renderer.c

event.o: event.c event.h
	$(GCC) -g -c event.c
	
model.o: model.c model.h const.h
	$(GCC) -g -c model.c

const.o: const.c const.h
	$(GCC) -g -c const.c

raster.o: raster.c raster.h
	$(GCC) -g -c raster.c
